# Generated by Django 4.1.3 on 2022-12-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('first_name', 'last_name')},
        ),
    ]
